
import { ChildrenProp } from '@/types';
import '../globals.css';
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout=({ children }:ChildrenProp)=> {
  return (
      <div>
        <h2>Next.js Assignment-1</h2>
        <div className="parent-button">
        <Link href="/Assignment-5/question-1">
          <button>Question-1</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-2">
          <button>Question-2</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-3">
          <button>Question-3</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-4">
          <button>Question-4</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-5">
          <button>Question-5</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-6">
          <button>Question-6</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-7">
          <button>Question-7</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-8">
          <button>Question-12</button>
        </Link>{"  "}
    
           <Link href="/Assignment-5/question-13">
          <button>Question-13</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-14">
          <button>Question-14</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-15">
          <button>Question-15</button>
        </Link>{"  "}
          <Link href="/Assignment-5/question-16">
          <button>Question-16</button>
        </Link>{"  "}
       </div>
        {children}
        </div>
  
       
  );
}

export default RootLayout;
