import LanguageContextProvider from "@/context/LanguageContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const questions = Array.from({ length: 19 }, (_, i) => i + 1);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          {questions.map((num) => (
            <Link key={num} href={`/Assignment-2/question-${num}`}>
              <button>Question-{num}</button>
            </Link>
          ))}
        </div>
          <LanguageContextProvider>
        {children}
        
     </LanguageContextProvider>  

      </body>
    </html>
  );
};

export default RootLayout;
