import LanguageContextProvider from "@/context/LanguageContext";
import type { Metadata } from "next";

import Link from "next/link";
import React from "react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const questions = Array.from({ length: 19 }, (_, i) => i + 1);

  return (
   <div>
        <div>
          {questions.map((num) => (
            <Link key={num} href={`/Assignment-2/question-${num}`}>
              <button>Question-{num}</button>
            </Link>
          ))}
        </div>
          <LanguageContextProvider>
        {children}
        
     </LanguageContextProvider>  

     </div> 
  );
};

export default RootLayout;
