import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ThemeContextProvider from "@/context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout=({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)=> {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Link href="/Assignment-1"> <button>Assignment-1</button>  </Link>
        <Link href="/Assignment-2"> <button>Assignment-2</button>  </Link>
        <Link href="/TicTacToe"> <button>TicTacToe</button>  </Link>
        
        <ThemeContextProvider>
        
            
        {children}
        </ThemeContextProvider>
      
      </body>
    </html>
  );
}

// const bodyStyle = {
//   display: "flex",
//   minHeight: "100vh",
//   margin: 0,
// }
// const sidebarStyle = {
//   width: "240px",
//   backgroundColor: "#1e293b", 
//   color: "white",
//   padding: "20px",
//   display: "flex",
//   flexDirection: "column",
// };

// const linkStyle = {
//   color: "white",
//   padding: "10px 16px",
//   border: "none",
//   borderRadius: "6px",
//   textAlign: "left",
//   fontWeight: "500",
//   cursor: "pointer",
//   textDecoration: "none",

// };

// const mainContentStyle = {
//   flex: 1,
//   padding: "40px",
// };

export default RootLayout;
