import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout=({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)=> {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
             <Link href="/Assignment-1/question-1"> <button>question-1</button>  </Link>
        <Link href="/Assignment-1/question-2"> <button>question-2</button>  </Link>
          <Link href="/Assignment-1/question-3"> <button>question-3</button>  </Link>
           <Link href="/Assignment-1/question-4"> <button>question-4</button>  </Link>
           <Link href="/Assignment-1/question-5"> <button>question-5</button>  </Link>
        {children}
   
      </body>
    </html>
  );
}
export default RootLayout;