
import "../globals.css";
import Link from "next/link";
import type { Metadata } from "next";
import { ChildrenProp } from "@/types";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProp) {
  return (

        <div>
          <h2>Next.js Assignment-1</h2>
          <div className="parent-button">
            <Link href="/Assignment-1/question-1">
              <button>Question-1</button>
            </Link>{" "}
            <Link href="/Assignment-1/question-2">
              <button>Question-2</button>
            </Link>{" "}
            <Link href="/Assignment-1/question-3">
              <button>Question-3</button>
            </Link>{" "}
            <Link href="/Assignment-1/question-4">
              <button>Question-4</button>
            </Link>{" "}
            <Link href="/Assignment-1/question-5">
              <button>Question-5</button>
            </Link>{" "}
            <Link href="/Assignment-1/question-6">
              <button>Question-6</button>
            </Link>{" "}
          </div>
          {children}
        </div>
  );
}
